spring:
  application:
    name: config-server
  cloud:
    config:
      server: 
        git: 
          uri: https://github.com/fymod/easy-spring-cloud/
          search-paths: 07-springcloud-config
          username: 
          password: 
server:
  port: 8770