server:
  port: 9112
spring:
  application:
    name: compose-eureka-client2
eureka:
  client:
    service-url:
      defaultZone: http://discovery:9110/eureka/
  instance:
    prefer-ip-address: true