server:
  port: 9010
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:9010/eureka/
spring:
  security:
    user:
      name: fymod
      password: 123456