server:
  port: 9023
spring:
  application:
    name: ribbon-web
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9020/eureka/
  instance:
    prefer-ip-address: true
ribbon-client:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule